### ISSUE TITLE
Add custom favicon to website

### ISSUE THREAD

**Issue by theritikchoure** [Abdullah-moiz/Job-Portal#2]
## Description:

As a website user, I would like to see a custom favicon for this website, to make it easier to identify and distinguish from other websites.

## Proposal:

- Create a new favicon in the desired image format (such as .png or .ico) with the appropriate dimensions (such as 32x32 pixels).
- Save the favicon image in the root directory of the website.
- Add the following code to the <head> section of the website's HTML code:

```
<link rel="icon" href="favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
```

Please let me know if you have any questions or concerns about this proposal.

**Comment by Abdullah-moiz** [comment]
This Issue is Resolved
